version: 2.1
orbs:
  node: circleci/node@4.0.0
  cypress: cypress-io/cypress@1
jobs:
  - build:
    working_directory: ~/gourmet-admin
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache
  - tests:
    steps:
      - run:
          name: Run unit and integration tests
          command: yarn test
      - run:
          name: Upload coverage to codecov
          command: yarn test:coverage
  - e2e:
    steps:
      - run:
        name: Run end to end tests
        command: yarn test:e2e:ci
      - store-artifacts:
          path: cypress_coverage
      - run:
        name: Upload end to end coverage to coveralls
        command: yarn e2e:coverage
workflows:
  version: 2
  unit_and_e2e_tests:
    jobs:
      - build
      - tests:
        requires:
          - build
      - e2e:
        requires:
          - tests
