version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build:
    working_directory: ~/gourmet-admin
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Tests
          command: yarn test
